=== jayamanghrani/Help/CITI Bank Code/outbound_utility/config/config_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/config_schema" xmlns:tns="http://www.example.org/config_schema" elementFormDefault="qualified">

    <complexType name="db_property">
    	<sequence>
    		<element name="driver" type="string"></element>
    		<element name="server_ip" type="string"></element>
    		<element name="port" type="int"></element>
    		<element name="schema_name" type="string"></element>
    		<element name="username" type="string"></element>
    		<element name="password" type="string"></element>
    	</sequence>
    </complexType>

    <complexType name="filecopy_property">
    	<sequence>
    		
    		<element name="fcopy_source" type="tns:fcopy_source_prop"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="fcopy_target" type="tns:fcopy_target_prop"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

      <complexType name="email_prop">
    	<sequence>
    		<element name="sender_email_adddress" type="string"></element>
    		<element name="mail_from" type="string"></element>
    		<element name="password" type="string"></element>
    		<element name="Receipent_list" type="string"></element>
    		<element name="message_subject" type="string"></element>
    		<element name="smtp_host" type="string"></element>
    		<element name="smtp_port" type="int"></element>
    		<element name="smtp_auth" type="boolean"></element>
    		<element name="debug" type="boolean"></element>
    		<element name="smtp_ssl_enable" type="boolean"></element>
    		<element name="message_body" type="string"></element>
    		<element name="message_signature" type="string"></element>
    	</sequence>
      </complexType>
    
    
    <complexType name="fcopy_source_prop">
    	<sequence>
    		<element name="s_path" type="string"></element>
    		<element name="s_fname" type="string"></element>
    		<element name="del_source_file" type="boolean"></element>
    		<element name="retry_attempts" type="int"></element>
    	</sequence>
    </complexType>

    <complexType name="fcopy_target_prop">
    	<sequence>
    		<element name="t_path" type="string"></element>
    		<element name="t_fname" type="string"></element>
    		<element name="t_ip" type="string"></element>
    		<element name="t_port" type="int"></element>
    		<element name="t_username" type="string"></element>
    		<element name="t_password" type="string"></element>
    		<element name="t_filenamePrefix" type="string"></element>
    	</sequence>
    </complexType>

    <element name="config" type="tns:config"></element>
    
    <complexType name="config">
    	<sequence>
    		<element name="email_prop" type="tns:email_prop" maxOccurs="1" minOccurs="1"></element>
    		<element name="db_prop" type="tns:db_property" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="fcopy_prop" type="tns:filecopy_property"
    			maxOccurs="unbounded" minOccurs="1">
    		</element>
    		<element name="fencrypt_prop" type="tns:fileencrypt_prop"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="fileencrypt_prop">
    	<sequence>
            <element name="shFile_Path" type="string"></element>
            <element name="plainFile_Path" type="string"></element>
            <element name="plainFileBackup_Path" type="string"></element>
    		<element name="encryptedFile_Path" type="string"></element>
    		<element name="encryptedFileBackup_Path" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== jayamanghrani/Help/CITI Bank Code/of_niaftp/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.example.org/config_schema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.example.org/config_schema config_schema.xsd ">
    <tns:email_prop>
    <tns:sender_email_adddress>of.support@newindia.co.in</tns:sender_email_adddress>
    <tns:mail_from>of.support@newindia.co.in</tns:mail_from>
    <tns:password>Oracle@123</tns:password>
    <tns:Receipent_list>u.nathwani@tcs.com</tns:Receipent_list>
    <tns:message_subject>SFTP exception occured</tns:message_subject>
    <tns:smtp_host>10.20.25.39</tns:smtp_host>
    <tns:smtp_port>25</tns:smtp_port>
    <tns:smtp_auth>true</tns:smtp_auth>
    <tns:debug>false</tns:debug>
    <tns:smtp_ssl_enable>false</tns:smtp_ssl_enable>
    <tns:message_body></tns:message_body>
    <tns:message_signature> CWISS-Oracle Finance Support Team
    IP :100067, Landline : 022-22708311
    Email: of.support@newindia.co.in</tns:message_signature>
  </tns:email_prop>
   <tns:db_prop>
    <tns:driver>oracle.jdbc.driver.OracleDriver</tns:driver>
    <tns:server_ip>10.90.90.57</tns:server_ip>
    <tns:port>1526</tns:port>
    <tns:schema_name>finprd</tns:schema_name>
    <tns:username>apps_readonly</tns:username>
    <tns:password>nia_readonly</tns:password>
  </tns:db_prop>
 <!--  <tns:db_prop>
    <tns:driver>oracle.jdbc.driver.OracleDriver</tns:driver>
    <tns:server_ip>10.10.3.246</tns:server_ip>
    <tns:port>1521</tns:port>
    <tns:schema_name>dgaapp</tns:schema_name>
    <tns:username>DGAAPP_UAT</tns:username>
    <tns:password>dgaapp12</tns:password>
  </tns:db_prop> -->
  
  <tns:fcopy_prop>
    <tns:fcopy_source>
      <tns:s_path></tns:s_path>
      <tns:s_fname></tns:s_fname>
      <tns:del_source_file>false</tns:del_source_file>
      <tns:retry_attempts>2</tns:retry_attempts>
    </tns:fcopy_source>
    <tns:fcopy_target>
      <tns:t_path>/NIAFTP/outbound_A/</tns:t_path>
      <tns:t_fname>null</tns:t_fname>
      <tns:t_ip>10.90.94.51</tns:t_ip>
      <tns:t_port>22</tns:t_port>
      <tns:t_username>ofsftp</tns:t_username>
      <tns:t_password>New@1234</tns:t_password>
      <tns:t_filenamePrefix>NIA_</tns:t_filenamePrefix>      
    </tns:fcopy_target>
  </tns:fcopy_prop>
</tns:config>

=== jayamanghrani/Help/ReportsCDSL_utility/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.example.org/config_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/config_schema config_schema.xsd ">
   <tns:email_prop>
    <tns:sender_email_adddress>of.support@newindia.co.in</tns:sender_email_adddress>
    <tns:mail_from>of.support@newindia.co.in</tns:mail_from>
    <tns:password>Oracle@123</tns:password>
    <tns:Receipent_list>zainab.kanchwala@tcs.com</tns:Receipent_list>
    <tns:message_subject>SFTP exception occured</tns:message_subject>
    <tns:smtp_host>10.20.25.39</tns:smtp_host>
    <tns:smtp_port>25</tns:smtp_port>
    <tns:smtp_auth>true</tns:smtp_auth>
    <tns:debug>false</tns:debug>
    <tns:smtp_ssl_enable>false</tns:smtp_ssl_enable>
    <tns:message_body></tns:message_body>
    <tns:message_signature> CWISS-Oracle Finance Support Team,
IP :100067, Landline : 022-22708311
Email: of.support@newindia.co.in</tns:message_signature>
  
  </tns:email_prop>
  <tns:db_prop>
    <tns:driver>oracle.jdbc.driver.OracleDriver</tns:driver>
    <tns:server_ip>10.90.33.8</tns:server_ip>
    <tns:port>1521</tns:port>
    <tns:schema_name>ofclone</tns:schema_name>
    <tns:username>apps_readonly</tns:username>
    <tns:password>nia_readonly</tns:password>
  </tns:db_prop>
  <tns:fcopy_prop>
    <tns:fcopy_source>
      <tns:s_path>D:\Workspace_Citibank\of_niaftp\of_db_file</tns:s_path>
      <tns:s_fname>o44414547.out</tns:s_fname>
      <tns:del_source_file>false</tns:del_source_file>
      <tns:retry_attempts>2</tns:retry_attempts>
    </tns:fcopy_source>
    <tns:fcopy_target>
      <tns:t_path>/NIAFTP/outbound_B/</tns:t_path>
      <tns:t_fname>null</tns:t_fname>
      <tns:t_ip>10.90.94.51</tns:t_ip>
      <tns:t_port>22</tns:t_port>
      <tns:t_username>ofsftp</tns:t_username>
      <tns:t_password>New@1234</tns:t_password>
      <tns:t_filenamePrefix>NIA_</tns:t_filenamePrefix>
      
    </tns:fcopy_target>
  </tns:fcopy_prop>
  
  <tns:fencrypt_prop>
  	<tns:shFile_Path>/NIAFTP/Application/SMIMETool/run/</tns:shFile_Path>
    <tns:plainFile_Path>/NIAFTP/outbound_A/</tns:plainFile_Path>
    <tns:plainFileBackup_Path>/NIAFTP/Backup/outbound_A_backup</tns:plainFileBackup_Path>
    <tns:encryptedFile_Path>/NIAFTP/outbound_B/</tns:encryptedFile_Path>
    <tns:encryptedFileBackup_Path>/NIAFTP/Backup/outbound_B_backup</tns:encryptedFileBackup_Path>
    
  </tns:fencrypt_prop>
  
</tns:config>

=== jayamanghrani/Help/cdsl config files/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:config xmlns:tns="http://www.example.org/config_schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/config_schema config_schema.xsd ">
  <tns:email_prop>
    <tns:sender_email_adddress>of.support@newindia.co.in</tns:sender_email_adddress>
    <tns:mail_from>orafin.support@newindia.co.in</tns:mail_from>
    <tns:password>Cisco$1234</tns:password>
    <tns:Receipent_list>sftp.support@newindia.co.in</tns:Receipent_list>
    <tns:message_subject>Error in SFTP of Report payment file transfer</tns:message_subject>
    <tns:smtp_host>mailhost.newindia.co.in</tns:smtp_host>
    <tns:smtp_port>25</tns:smtp_port>
    <tns:smtp_auth>true</tns:smtp_auth>
    <tns:debug>false</tns:debug>
    <tns:smtp_ssl_enable>false</tns:smtp_ssl_enable>
    <tns:message_body></tns:message_body>
    <tns:message_signature>CWISS-Oracle Finance Support Team,
IP :100067, Landline : 022-22708311
Email: of.support@newindia.co.in</tns:message_signature>
  </tns:email_prop>
   <tns:db_prop>
    <tns:driver></tns:driver>
    <tns:server_ip></tns:server_ip>
    <tns:port></tns:port>
    <tns:schema_name></tns:schema_name>
    <tns:username></tns:username>
    <tns:password></tns:password>
  </tns:db_prop>
  <tns:fcopy_prop>
    <tns:fcopy_source>
      <tns:s_path>/PNBSFTP/Backup/Test</tns:s_path> 
      <tns:s_fname></tns:s_fname>
      <tns:del_source_file>false</tns:del_source_file>
      <tns:retry_attempts>6</tns:retry_attempts>
    </tns:fcopy_source>
    <tns:fcopy_target> 
      <tns:t_path>/</tns:t_path>
      <tns:t_fname>null</tns:t_fname>
      <tns:t_ip>61.95.148.22</tns:t_ip>
      <tns:t_port>22</tns:t_port>
      <tns:t_username>NIA</tns:t_username>
      <tns:t_password>Sep_2017</tns:t_password>
    </tns:fcopy_target>
  </tns:fcopy_prop>
  
  <tns:fencrypt_prop>
    <tns:shFile_Path></tns:shFile_Path>
    <tns:plainFile_Path></tns:plainFile_Path>
    <tns:plainFileBackup_Path></tns:plainFileBackup_Path>
    <tns:encryptedFile_Path></tns:encryptedFile_Path>
    <tns:encryptedFileBackup_Path></tns:encryptedFileBackup_Path>
    
  </tns:fencrypt_prop>
  
</tns:config>
